/*
 * Copyright 2017-2024 JetBrains s.r.o. Use of this source code is governed by the Apache 2.0 license.
 */

package kotlinx.serialization

import kotlin.reflect.typeOf
import kotlin.test.*

/**
 * Tests for improved error messages when the serialization compiler plugin was not applied,
 * which is the scenario described in KT-47384.
 *
 * In Kotlin script files (.main.kts), adding a @file:DependsOn(...) for the serialization
 * runtime library is possible, but the compiler plugin cannot be applied via
 * @file:CompilerOptions("-Xplugin=...") because the script compiler ignores this option.
 * As a result, @Serializable-annotated classes fail at runtime because no serializer
 * was generated by the compiler plugin.
 *
 * The [AnnotatedWithoutPlugin] Java class simulates this scenario: it has the @Serializable
 * annotation but no compiler-generated serializer (the Kotlin serialization plugin does not
 * process Java source files).
 */
class MissingPluginErrorMessageTest {

    @Test
    fun testErrorMessageMentionsCompilerPlugin() {
        // AnnotatedWithoutPlugin is a Java class with @Serializable annotation but without
        // a compiler-generated serializer. This simulates the script environment where
        // the compiler plugin is not applied.
        val exception = assertFailsWith<SerializationException> {
            serializer(typeOf<AnnotatedWithoutPlugin>())
        }
        val message = exception.message ?: fail("Exception message must not be null")
        assertTrue(
            "compiler plugin" in message,
            "Expected error message to mention 'compiler plugin', but was:\n$message"
        )
        assertTrue(
            "AnnotatedWithoutPlugin" in message,
            "Expected error message to contain class name, but was:\n$message"
        )
    }
}
